export const PRODUCT_INFO_FAILED = "PRODUCT_INFO_FAILED";
export const PRODUCT_INFO_FETCHED = "PRODUCT_INFO_FETCHED";
export const PRODUCT_INFO_FETCHING = "PRODUCT_INFO_FETCHING";
export const PRODUCT_INFO_INVALID = "PRODUCT_INFO_INVALID";
export const CARD_ADD = "CARD_ADD";
export const REDUCE_QUANTIY = "REDUCE_QUANTIY";
export const CARD_REMOVE = "CARD_REMOVE";
export const CARD_DESTROY_ITEM = "CARD_DESTROY_ITEM";